### ISSUE TITLE
Feature - remove NextJs and use Vite

### ISSUE THREAD

**Issue by TymurPysarevych** [Braun-Johannes/home#13]
To sum up, Next.js and Vite.js are both strong web app development frameworks. Next.js is an excellent option for projects where SEO is a top concern or when it's imperative to present the user with a meaningful page as soon as possible due to its server-side rendering and static site generation features. It's also a fantastic fit for websites with often updated material or projects with dynamic content that adjusts based on user activities. Which is not the case here...

On the other hand, Vite.js is a great option for projects where you want to maintain a modest server load and a quick development workflow because of its emphasis on client-side rendering and dynamic imports. Vite.js is used for Single-page applications (SPAs) and projects where a large portion of the website's content is static. And this fine project is a SPA 😉

I already prepared a Pull-Request, I just need permission to create one.

**Comment by Braun-Johannes** [comment]
Thanks for the explanation first of. 
I think i understood the whole thing, so as my site is in fact static and maybe 4 times a year updated or changed there is no need to use Next.

I added you as a collaborator to the repository. you should be able to create a pull request now. I think. 🥦
